/**
 * Per-lesson Remotion render jobs.
 * Every lesson maps to a SPECIFIC composition with props tailored to its exact content.
 *
 * posterUrl always points to /assets/lessons/{id}.svg  — the dedicated lesson poster
 * illustration generated by scripts/generate-lesson-illustrations.ts.
 * Story-illustration pages (/assets/story-illustrations/) belong to the
 * ChildrensBook interactive storybook component and are intentionally NOT used here.
 */

export type RenderJob = {
    id: string;
    compositionId:
    | "PayoffDiagramVideo"
    | "GreekVisualizerVideo"
    | "GreekCurveVideo"
    | "OptionTicketVideo"
    | "MarketMechanicsVideo"
    | "TechnicalChartVideo"
    | "FundamentalDashboardVideo"
    | "StrategyBuilderVideo"
    | "CoreConceptVideo"
    | "StocksSlideVideo"
    | "PersonalFinanceVideo";
    props: Record<string, unknown>;
};

const makeCandles = (trend: "up" | "down" | "flat" = "flat") =>
    Array.from({ length: 60 }, (_, i) => {
        const base = 150 + (trend === "up" ? i * 0.3 : trend === "down" ? -i * 0.3 : Math.sin(i * 0.4) * 5);
        const o = base + (Math.random() - 0.5) * 1.5;
        const c = base + (Math.random() - 0.5) * 1.5;
        return { open: o, close: c, high: Math.max(o, c) + Math.random() * 1.2, low: Math.min(o, c) - Math.random() * 1.2, volume: Math.random() * 1_200_000 };
    });

const makeOrderBook = () =>
    Array.from({ length: 30 }, (_, i) => ({
        price: 150.5 - i * 0.1 + 1.5,
        bidSize: Math.floor(Math.random() * 500),
        askSize: Math.floor(Math.random() * 500),
    }));

export const lessonRenderJobs: RenderJob[] = [

    // ─── OPTIONS BASICS ────────────────────────────────────────────────────────

    {
        id: "basics-flow",
        compositionId: "PayoffDiagramVideo",
        props: {
            title: "Options Flow in 90s",
            subtitle: "Watch payoff reshape as price moves",
            posterUrl: "/assets/lessons/basics-flow.svg",
            accent: "#10b981",
            strategyType: "long-call",
            underlyingPrice: 150,
            strike1: 150,
            premium: 3.2,
        },
    },
    {
        id: "options-chain-reading",
        compositionId: "MarketMechanicsVideo",
        props: {
            title: "Reading the Options Chain",
            subtitle: "Bid/Ask · Volume · Open Interest",
            subjectLabel: "Market Mechanics",
            posterUrl: "/assets/lessons/options-chain-reading.svg",
            accent: "#3b82f6",
            mechanicType: "option-chain",
            dataPoints: makeOrderBook(),
        },
    },
    {
        id: "strike-price-mastery",
        compositionId: "OptionTicketVideo",
        props: {
            title: "Strike Selection",
            subtitle: "ITM, ATM, and OTM — what they mean",
            posterUrl: "/assets/lessons/strike-price-mastery.svg",
            accent: "#3b82f6",
            ticketType: "strike-zones",
            underlyingPrice: 150,
        },
    },
    {
        id: "contracts-walkthrough",
        compositionId: "OptionTicketVideo",
        props: {
            title: "Contracts, Strikes & Expirations",
            subtitle: "Intrinsic vs. extrinsic value live",
            posterUrl: "/assets/lessons/contracts-walkthrough.svg",
            accent: "#a78bfa",
            ticketType: "contract-decomposition",
            underlyingPrice: 150,
            strikePrice: 148,
            daysToExpiry: 30,
        },
    },

    // ─── GREEKS ────────────────────────────────────────────────────────────────

    {
        id: "delta-scaling",
        compositionId: "GreekVisualizerVideo",
        props: {
            title: "Delta Scaling Drill",
            subtitle: "Maintain target portfolio delta as price drifts",
            subjectLabel: "The Greeks",
            posterUrl: "/assets/lessons/delta-scaling.svg",
            accent: "#10b981",
            glow: "rgba(16,185,129,0.65)",
            greekName: "Delta",
            startValue: 0.15,
            endValue: 0.85,
            explanation: "Delta measures the expected price change per $1 move in the underlying. A 0.85Δ option moves almost dollar-for-dollar with the stock.",
        },
    },
    {
        id: "gamma-acceleration",
        compositionId: "GreekCurveVideo",
        props: {
            title: "Gamma Acceleration",
            subtitle: "See delta speed up as price nears the strike",
            posterUrl: "/assets/lessons/gamma-acceleration.svg",
            accent: "#f43f5e",
            greekType: "gamma",
            strike: 150,
        },
    },
    {
        id: "theta-clock",
        compositionId: "GreekVisualizerVideo",
        props: {
            title: "Theta Clock",
            subtitle: "Time decay chewing through premium daily",
            subjectLabel: "The Greeks",
            posterUrl: "/assets/lessons/theta-clock.svg",
            accent: "#eab308",
            glow: "rgba(234,179,8,0.65)",
            greekName: "Theta",
            startValue: -0.04,
            endValue: -0.28,
            explanation: "Theta accelerates as expiration approaches — especially for ATM options. Track how fast the clock is ticking relative to your P/L.",
        },
    },
    {
        id: "vega-sensitivity",
        compositionId: "GreekCurveVideo",
        props: {
            title: "Vega Sensitivity",
            subtitle: "Short-dated vs long-dated response to IV shifts",
            posterUrl: "/assets/lessons/vega-sensitivity.svg",
            accent: "#a855f7",
            greekType: "vega",
            ivLow: 20,
            ivHigh: 55,
        },
    },
    {
        id: "rho-rate-risk",
        compositionId: "GreekCurveVideo",
        props: {
            title: "Rho Rate Risk",
            subtitle: "How rate hikes tilt call and put pricing",
            posterUrl: "/assets/lessons/rho-rate-risk.svg",
            accent: "#0ea5e9",
            greekType: "rho",
            rateLow: 3.5,
            rateHigh: 6.5,
        },
    },

    // ─── STRATEGY ─────────────────────────────────────────────────────────────

    {
        id: "vertical-spreads",
        compositionId: "PayoffDiagramVideo",
        props: {
            title: "Vertical Spread Builder",
            subtitle: "Defined risk · Defined reward",
            posterUrl: "/assets/lessons/vertical-spreads.svg",
            accent: "#3b82f6",
            strategyType: "vertical",
            underlyingPrice: 150,
            strike1: 150,
            strike2: 157,
            premium: 3.5,
        },
    },
    {
        id: "iron-condor",
        compositionId: "PayoffDiagramVideo",
        props: {
            title: "Iron Condor Range Plan",
            subtitle: "Sell a defined range, collect credit",
            posterUrl: "/assets/lessons/iron-condor.svg",
            accent: "#f59e0b",
            strategyType: "iron-condor",
            underlyingPrice: 150,
            strike1: 135,
            strike2: 142,
            strike3: 158,
            strike4: 165,
            premium: 3.2,
        },
    },
    {
        id: "butterfly-spreads",
        compositionId: "PayoffDiagramVideo",
        props: {
            title: "Butterfly Target Play",
            subtitle: "Aim for the price pin at expiry",
            posterUrl: "/assets/lessons/butterfly-spreads.svg",
            accent: "#ec4899",
            strategyType: "butterfly",
            underlyingPrice: 150,
            strike1: 143,
            strike2: 150,
            strike3: 157,
            premium: 1.5,
        },
    },
    {
        id: "calendar-diagonal",
        compositionId: "PayoffDiagramVideo",
        props: {
            title: "Calendar & Diagonal Timing",
            subtitle: "Pair expirations to harness time decay",
            posterUrl: "/assets/lessons/calendar-diagonal.svg",
            accent: "#8b5cf6",
            strategyType: "calendar",
            underlyingPrice: 150,
            strike1: 150,
            premium: 2.8,
        },
    },
    {
        id: "straddle-strangle",
        compositionId: "PayoffDiagramVideo",
        props: {
            title: "Straddle & Strangle",
            subtitle: "Trade big moves with long volatility",
            posterUrl: "/assets/lessons/straddle-strangle.svg",
            accent: "#ef4444",
            strategyType: "straddle",
            underlyingPrice: 150,
            strike1: 150,
            strike2: 155,
            premium: 4.2,
            premium2: 3.8,
        },
    },
    {
        id: "risk-sizer",
        compositionId: "CoreConceptVideo",
        props: {
            title: "Risk Per Trade Sizing",
            subtitle: "Never blow up on a single trade",
            subjectLabel: "Strategy",
            posterUrl: "/assets/lessons/risk-sizer.svg",
            accent: "#f97316",
            glow: "rgba(249,115,22,0.65)",
            conceptHeadline: "Risk exactly 1–2% of your account per trade. Make that the only rule you never break.",
        },
    },
    {
        id: "exit-playbook",
        compositionId: "CoreConceptVideo",
        props: {
            title: "Exit Playbook Reps",
            subtitle: "Stop · Target · Time exits compared",
            subjectLabel: "Strategy",
            posterUrl: "/assets/lessons/exit-playbook.svg",
            accent: "#06b6d4",
            glow: "rgba(6,182,212,0.65)",
            conceptHeadline: "Define your exit before you enter. A trade without a plan is just gambling with extra steps.",
        },
    },

    // ─── MARKET MECHANICS ──────────────────────────────────────────────────────

    {
        id: "bid-ask-reality",
        compositionId: "MarketMechanicsVideo",
        props: {
            title: "Bid/Ask Reality Check",
            subtitle: "Slippage cost in thin names",
            subjectLabel: "Market Mechanics",
            posterUrl: "/assets/lessons/bid-ask-reality.svg",
            accent: "#3b82f6",
            mechanicType: "order-book",
            dataPoints: makeOrderBook(),
        },
    },
    {
        id: "tape-speed",
        compositionId: "MarketMechanicsVideo",
        props: {
            title: "Tape Speed & Volume",
            subtitle: "Flow acceleration signals momentum shifts",
            subjectLabel: "Market Mechanics",
            posterUrl: "/assets/lessons/tape-speed.svg",
            accent: "#f59e0b",
            mechanicType: "tape",
            dataPoints: makeOrderBook(),
        },
    },
    {
        id: "borrow-locate",
        compositionId: "MarketMechanicsVideo",
        props: {
            title: "Borrow & Locate Steps",
            subtitle: "Fees, recalls, and short squeeze risk",
            subjectLabel: "Market Mechanics",
            posterUrl: "/assets/lessons/borrow-locate.svg",
            accent: "#ef4444",
            mechanicType: "order-book",
            dataPoints: makeOrderBook(),
        },
    },
    {
        id: "short-risk",
        compositionId: "MarketMechanicsVideo",
        props: {
            title: "Short Risk Control",
            subtitle: "Buy-to-cover triggers and halt coverage",
            subjectLabel: "Market Mechanics",
            posterUrl: "/assets/lessons/short-risk.svg",
            accent: "#f43f5e",
            mechanicType: "order-book",
            dataPoints: makeOrderBook(),
        },
    },
    {
        id: "order-types",
        compositionId: "MarketMechanicsVideo",
        props: {
            title: "Order Types Mastery",
            subtitle: "Market, Limit, Stop, Trailing Stop",
            subjectLabel: "Market Mechanics",
            posterUrl: "/assets/lessons/order-types.svg",
            accent: "#3b82f6",
            mechanicType: "order-book",
            dataPoints: makeOrderBook(),
        },
    },

    // ─── TECHNICAL ANALYSIS ────────────────────────────────────────────────────

    {
        id: "candlesticks-101",
        compositionId: "TechnicalChartVideo",
        props: {
            title: "Candlestick Patterns",
            subtitle: "Doji · Hammer · Engulfing · Morning Star",
            subjectLabel: "Technical Analysis",
            posterUrl: "/assets/lessons/candlesticks-101.svg",
            accent: "#f59e0b",
            indicator: "candlesticks",
            candles: makeCandles("flat"),
        },
    },
    {
        id: "support-resistance",
        compositionId: "TechnicalChartVideo",
        props: {
            title: "Support & Resistance",
            subtitle: "Key levels, breakouts, polarity principle",
            subjectLabel: "Technical Analysis",
            posterUrl: "/assets/lessons/support-resistance.svg",
            accent: "#f59e0b",
            indicator: "support-resistance",
            candles: makeCandles("up"),
        },
    },
    {
        id: "momentum-box",
        compositionId: "TechnicalChartVideo",
        props: {
            title: "Breakout Momentum Box",
            subtitle: "High-volume breakout + VWAP entry timing",
            subjectLabel: "Technical Analysis",
            posterUrl: "/assets/lessons/momentum-box.svg",
            accent: "#10b981",
            indicator: "momentum",
            candles: makeCandles("up"),
        },
    },
    {
        id: "rsi-macd",
        compositionId: "TechnicalChartVideo",
        props: {
            title: "RSI + MACD Confirmation",
            subtitle: "Stack oscillators for confluence entries",
            subjectLabel: "Technical Analysis",
            posterUrl: "/assets/lessons/rsi-macd.svg",
            accent: "#6366f1",
            indicator: "rsi-macd",
            candles: makeCandles("down"),
        },
    },
    {
        id: "rsi-macd-mastery",
        compositionId: "TechnicalChartVideo",
        props: {
            title: "RSI & MACD Mastery",
            subtitle: "Divergences, overbought, crossover timing",
            subjectLabel: "Technical Analysis",
            posterUrl: "/assets/lessons/rsi-macd-mastery.svg",
            accent: "#6366f1",
            indicator: "rsi-macd",
            candles: makeCandles("flat"),
        },
    },
    {
        id: "bollinger-volume-101",
        compositionId: "TechnicalChartVideo",
        props: {
            title: "Bollinger Bands & Volume",
            subtitle: "Squeeze → Breakout → Band Walk",
            subjectLabel: "Technical Analysis",
            posterUrl: "/assets/lessons/bollinger-volume-101.svg",
            accent: "#a855f7",
            indicator: "bollinger",
            candles: makeCandles("up"),
        },
    },
    {
        id: "moving-averages",
        compositionId: "TechnicalChartVideo",
        props: {
            title: "Moving Averages Strategy",
            subtitle: "Golden Cross · Death Cross · MA Bounce",
            subjectLabel: "Technical Analysis",
            posterUrl: "/assets/lessons/moving-averages.svg",
            accent: "#f59e0b",
            indicator: "moving-averages",
            candles: makeCandles("up"),
        },
    },

    // ─── FUNDAMENTALS ──────────────────────────────────────────────────────────

    {
        id: "fundamentals-earnings",
        compositionId: "FundamentalDashboardVideo",
        props: {
            title: "Earnings Quality Scanner",
            subtitle: "Revenue · Margins · Guidance quality",
            subjectLabel: "Fundamentals",
            posterUrl: "/assets/lessons/fundamentals-earnings.svg",
            accent: "#10b981",
            metric: "EPS Beat",
            value: "+$0.42",
        },
    },
    {
        id: "valuation-vs-vol",
        compositionId: "FundamentalDashboardVideo",
        props: {
            title: "Valuation vs. Volatility",
            subtitle: "P/E compression linked to IV shifts",
            subjectLabel: "Fundamentals",
            posterUrl: "/assets/lessons/valuation-vs-vol.svg",
            accent: "#f59e0b",
            metric: "Implied Vol",
            value: "82.4%",
        },
    },
    {
        id: "liquidity-runway",
        compositionId: "FundamentalDashboardVideo",
        props: {
            title: "Liquidity Runway Scorecard",
            subtitle: "Cash runway · Debt walls · Buffers",
            subjectLabel: "Fundamentals",
            posterUrl: "/assets/lessons/liquidity-runway.svg",
            accent: "#3b82f6",
            metric: "Cash Runway",
            value: "18 months",
        },
    },
    {
        id: "fundamental-analysis-101",
        compositionId: "FundamentalDashboardVideo",
        props: {
            title: "Financial Statements Guide",
            subtitle: "Income · Balance Sheet · Cash Flow",
            subjectLabel: "Fundamentals",
            posterUrl: "/assets/lessons/fundamental-analysis-101.svg",
            accent: "#10b981",
            metric: "Free Cash Flow",
            value: "$4.2B",
        },
    },
    {
        id: "valuation-ratios-101",
        compositionId: "FundamentalDashboardVideo",
        props: {
            title: "Valuation Ratios Dashboard",
            subtitle: "P/E · P/B · EV/EBITDA · PEG",
            subjectLabel: "Fundamentals",
            posterUrl: "/assets/lessons/valuation-ratios-101.svg",
            accent: "#a855f7",
            metric: "P/E Ratio",
            value: "34.2×",
        },
    },
    {
        id: "earnings-analysis-101",
        compositionId: "FundamentalDashboardVideo",
        props: {
            title: "Earnings & Catalysts Tracker",
            subtitle: "Beat/miss signals and catalyst calendars",
            subjectLabel: "Fundamentals",
            posterUrl: "/assets/lessons/earnings-analysis-101.svg",
            accent: "#f43f5e",
            metric: "Revenue Beat",
            value: "+$420M",
        },
    },

    // ─── EVENTS ────────────────────────────────────────────────────────────────

    {
        id: "events-earnings",
        compositionId: "FundamentalDashboardVideo",
        props: {
            title: "Earnings Gap Defense",
            subtitle: "IV crush paths and post-earnings adjustments",
            subjectLabel: "Events",
            posterUrl: "/assets/lessons/events-earnings.svg",
            accent: "#ef4444",
            metric: "Expected Move",
            value: "±$12.50",
        },
    },
    {
        id: "macro-vol",
        compositionId: "FundamentalDashboardVideo",
        props: {
            title: "Macro Print Volatility",
            subtitle: "CPI · FOMC · Term structure whipsaws",
            subjectLabel: "Events",
            posterUrl: "/assets/lessons/macro-vol.svg",
            accent: "#0ea5e9",
            metric: "VIX Level",
            value: "26.8",
        },
    },

    // ─── STOCKS ────────────────────────────────────────────────────────────────

    {
        id: "stocks-101",
        compositionId: "StocksSlideVideo",
        props: {
            title:        "What Is a Stock?",
            subtitle:     "Equity ownership, exchanges, bull/bear cycles",
            subjectLabel: "Stock Basics",
            // posterUrl is hardcoded inside StocksSlideVideo (uses assets/lessons/stocks-101.svg)
            accent:       "#6366f1",
            glow:         "rgba(99,102,241,0.65)",
        },
    },
    {
        id: "sourdough-basics",
        compositionId: "CoreConceptVideo",
        props: {
            title: "Framework Demo",
            subtitle: "Domain-agnostic lesson engine verification",
            subjectLabel: "Developer Tools",
            posterUrl: "/assets/lessons/sourdough-basics.svg",
            accent: "#64748b",
            glow: "rgba(100,116,139,0.65)",
            conceptHeadline: "Options Educator Framework v2 — content engine verified. Lesson generation is domain-agnostic.",
        },
    },

    // ─── GREEKS OVERVIEW ──────────────────────────────────────────────────────

    {
        id: "intro-greeks",
        compositionId: "GreekVisualizerVideo",
        props: {
            title: "The Five Greeks",
            subtitle: "Delta · Gamma · Theta · Vega · Rho — your options toolkit",
            subjectLabel: "Options Greeks",
            posterUrl: "/assets/lessons/delta-scaling.svg",
            accent: "#6366f1",
            glow: "rgba(99,102,241,0.65)",
            greekName: "Delta",
            startValue: 0.05,
            endValue: 0.95,
            explanation: "The Greeks are five measurements that tell you exactly how sensitive your option is to price changes, time passing, volatility shifts, and interest rates. Master them and you master options.",
        },
    },

    // ─── PERSONAL FINANCE ──────────────────────────────────────────────────────

    {
        id: "pf-budgeting-101",
        compositionId: "PersonalFinanceVideo",
        props: {
            title: "Budgeting Basics",
            subtitle: "The 50·30·20 rule animated",
            posterUrl: "/assets/lessons/pf-budgeting-101.svg",
            accent: "#6366f1",
            financeType: "budget",
        },
    },
    {
        id: "pf-cashflow-basics",
        compositionId: "PersonalFinanceVideo",
        props: {
            title: "Cash Flow Mapping",
            subtitle: "Payday vs bills: never go negative",
            posterUrl: "/assets/lessons/pf-cashflow-basics.svg",
            accent: "#06b6d4",
            financeType: "cashflow",
        },
    },
    {
        id: "pf-savings-basics",
        compositionId: "PersonalFinanceVideo",
        props: {
            title: "Savings Foundations",
            subtitle: "Automated weekly contributions + compound growth",
            posterUrl: "/assets/lessons/pf-savings-basics.svg",
            accent: "#10b981",
            financeType: "savings",
        },
    },
];
