#!/usr/bin/env python3
"""ONE STUDIO / SIX ENGINES - a ~90s showreel where every chapter is freshly
generated by a different engine of this repo's studio, today:

  01  LTX-2 on the local GPU        (new Options City atmosphere shot)
  02  Veo 3.1 via Google Flow       (new browser-driven generation)
  03  Manim via the animation pipeline (payoff-curve math animation)
  04  Remotion React templates      (GreekCurveVideo, full render)
  05  The motion-graphics promo engine (fresh mg.Promo sequence)
  06  The code-composed score       (the audio bed itself)

Nothing is reused from earlier renders - the point of the reel is that the
studio made every frame and every sample on demand. Title cards and engine
labels are drawn (PIL), never generated, per this repo's no-generated-text
rule.

Each generator is a subcommand so the long ones can run in parallel:

    studio_showreel90.py --make ltx        # GPU lane
    studio_showreel90.py --make flow       # needs the Flow Chrome (CDP)
    studio_showreel90.py --make manim      # python3.11 + manim
    studio_showreel90.py --make remotion   # node
    studio_showreel90.py --make promo      # CPU only
    studio_showreel90.py --make score      # CPU only
    studio_showreel90.py --make assemble   # once all six exist
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
CINEMATIC = HERE.parent
sys.path.insert(0, str(CINEMATIC / "engine"))
sys.path.insert(0, str(CINEMATIC))

ROOT = CINEMATIC.parent
OUT_ROOT = Path.home() / "LTX-Renders" / "studio-showreel"
WORK = OUT_ROOT / "work"
FINAL = OUT_ROOT / "studio_showreel90.mp4"
FPS = 24

ANIM_PYTHON = "/opt/homebrew/bin/python3.11"
REMOTION_BIN = ROOT / "remotion-videos" / "node_modules" / ".bin" / "remotion"

TRAILER = HERE / "ltx25_optionseducator_trailer60.py"

# The chapters, in cut order. Each generator writes its clip to WORK/<key>.mp4.
CHAPTERS = [
    ("ltx", "LTX-2 · LOCAL GPU", "10-second worlds generated on this machine"),
    ("flow", "VEO 3.1 · GOOGLE FLOW", "hero shots from a browser-driven cloud model"),
    ("manim", "MANIM · ANIMATION PIPELINE", "math that draws itself"),
    (
        "remotion",
        "REMOTION · REACT TEMPLATES",
        "20 lesson templates, rendered from code",
    ),
    ("promo", "MOTION GFX · PROMO ENGINE", "frame-by-frame graphics, no model at all"),
]

# Seed 91011 with a harbour/waterfront prompt produced a solid-colour broken
# encode (the backend's known failure mode - see the media_plaza note in the
# trailer script). This prompt stays inside vocabulary the backend has
# reliably rendered: aerial dusk city, traffic, trams, drones - no water.
LTX_SEED = 91314  # 91213 hit the broken-encode backend state (fixed by
# restarting LTX Desktop, which had a half-applied auto-update running)
LTX_PROMPT_CORE = (
    "Slow aerial glide at dusk across a stylised open-world game city: tan "
    "and deep blue geometric towers with glowing teal display panels, wide "
    "dark avenues traced in bright cyan lane lines, dense streams of small "
    "stylised cars flowing in both directions, trams crossing between "
    "districts, pedestrians on the sidewalks, drones drifting between "
    "rooftop antennae. "
)

FLOW_PROMPT_CORE = (
    "Dawn breaks over a stylised low-poly game city seen from a high rooftop: "
    "the sun crests behind a great domed hall on the horizon, long volumetric "
    "light shafts sweep across tan geometric towers whose teal display panels "
    "flicker awake one by one, dense cyan-lit traffic starts to flow along "
    "every avenue below, trams glide out of depots, flocks of drones lift off "
    "from rooftops into the pink and gold sky. "
)


def trailer_module():
    spec = importlib.util.spec_from_file_location("trailer_mod", TRAILER)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _done(key: str) -> Path:
    return WORK / f"{key}.mp4"


# ── generators ──────────────────────────────────────────────────────────────


def make_ltx() -> Path:
    mod = trailer_module()
    token = mod.auth_token()
    mod.ensure_ready(mod.BASE_URL, token)
    # Two custom prompts at 540p produced the backend's known broken-encode
    # failure (19KB solid-colour files) back to back. Every payload this model
    # has demonstrably rendered lately was the trailer's own video_payload()
    # shape at 720p - so the showreel shot uses exactly that shape, with the
    # proven city_reveal act and a fresh seed for fresh footage.
    act = next(a for a in mod.ATMOSPHERE if a["id"] == "city_reveal")
    fresh_act = {**act, "seed": LTX_SEED}
    args = argparse.Namespace(resolution="720p", source_seconds=10)
    payload = mod.video_payload(fresh_act, args)
    print("LTX: generating showreel shot...", flush=True)
    started = time.time()
    result = mod.request("POST", f"{mod.BASE_URL}/api/generate", token, payload, 3600)
    print(f"LTX: done in {time.time() - started:.0f}s", flush=True)
    src = result.get("video_path")
    if result.get("status") != "complete" or not src:
        raise SystemExit(f"LTX generation failed: {json.dumps(result)[:300]}")
    (WORK / "ltx_result.json").write_text(json.dumps(result, indent=2))
    # Never trust "status": "complete" - the backend has produced solid-colour
    # broken encodes before. Reject anything without real frame-to-frame motion.
    probe = subprocess.run(
        [
            "ffmpeg",
            "-v",
            "info",
            "-i",
            src,
            "-vf",
            "freezedetect=n=0.003:d=4",
            "-an",
            "-f",
            "null",
            "-",
        ],
        capture_output=True,
        text=True,
    )
    if "freeze_start" in probe.stderr:
        raise SystemExit(
            f"LTX returned a broken (static) clip at {src} - regenerate with "
            "a different seed/prompt. Not copying it into the reel."
        )
    subprocess.run(["cp", src, str(_done("ltx"))], check=True)
    return _done("ltx")


def make_flow() -> Path:
    import media
    from providers.flow_browser import FlowBrowserProvider

    mod = trailer_module()
    spec = media.MediaSpec(
        id="showreel_flow",
        kind=media.VIDEO,
        prompt=(
            FLOW_PROMPT_CORE + mod.LOOK + " No visible text, letters, words, "
            "numbers, captions, signs, screens, watermark, or logos."
        ),
        seconds=8,
    )
    provider = FlowBrowserProvider(timeout_s=900)

    def wait(job):
        time.sleep(10)
        print(".", end="", flush=True)

    fetched = provider.generate(spec, WORK, wait=wait)
    subprocess.run(["mv", str(fetched), str(_done("flow"))], check=True)
    return _done("flow")


def make_manim() -> Path:
    scene_file = ROOT / "video-pipeline" / "examples" / "example_payoff_curve.py"
    media_dir = WORK / "manim_media"
    subprocess.run(
        [
            ANIM_PYTHON,
            "-m",
            "manim",
            "render",
            "-qm",
            "--fps",
            str(FPS),
            "-r",
            "1280,720",
            "--media_dir",
            str(media_dir),
            "-o",
            "manim_payoff.mp4",
            str(scene_file),
            "PayoffDiagramScene",
        ],
        check=True,
    )
    hits = sorted(media_dir.glob("videos/**/manim_payoff.mp4"))
    if not hits:
        raise SystemExit("manim rendered nothing (see manim_media/)")
    subprocess.run(["cp", str(hits[0]), str(_done("manim"))], check=True)
    return _done("manim")


def make_remotion() -> Path:
    subprocess.run(
        [
            str(REMOTION_BIN),
            "render",
            str(ROOT / "remotion-videos" / "src" / "index.ts"),
            "GreekCurveVideo",
            str(_done("remotion")),
        ],
        check=True,
    )
    return _done("remotion")


def make_promo() -> Path:
    from stages import motiongfx as mg

    p = mg.Promo(WORK / "_mg_frames")
    p.title("The Promo Engine", "graphics drawn frame by frame")
    p.ticker()
    p.candles()
    p.payoff()
    p.kinetic(["No model.", "No prompt.", "Just code."])
    print(f"promo: {p.n} frames = {p.n / FPS:.1f}s", flush=True)
    p.encode(_done("promo"))
    return _done("promo")


def make_score() -> Path:
    out = WORK / "score.wav"
    subprocess.run(
        [sys.executable, str(HERE / "compose_trailer_score.py"), str(out)],
        check=True,
    )
    return out


# ── drawn cards and labels ──────────────────────────────────────────────────


def _font(size: int, bold: bool = True):
    from PIL import ImageFont

    for cand in (
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
        if bold
        else "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/System/Library/Fonts/Avenir Next.ttc",
        "/System/Library/Fonts/Helvetica.ttc",
    ):
        try:
            return ImageFont.truetype(cand, size)
        except Exception:  # noqa: BLE001
            continue
    return ImageFont.load_default()


def _card(lines: list[tuple[str, int, str]], out: Path) -> Path:
    """A drawn 1280x720 card: [(text, font_size, colour_hex)] stacked centred."""
    from PIL import Image, ImageDraw

    img = Image.new("RGB", (1280, 720), "#0b1020")
    d = ImageDraw.Draw(img)
    d.rectangle([120, 352, 360, 356], fill="#6366f1")
    total = sum(sz + 26 for _, sz, _ in lines)
    y = (720 - total) / 2
    for text, sz, colour in lines:
        f = _font(sz)
        w = d.textlength(text, font=f)
        d.text(((1280 - w) / 2, y), text, font=f, fill=colour)
        y += sz + 26
    img.save(out)
    return out


def _label(engine_no: int, name: str, sub: str, out: Path) -> Path:
    """Lower-third RGBA overlay for one chapter."""
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", (1280, 720), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 560, 1280, 720], fill=(11, 16, 32, 165))
    d.rectangle([64, 588, 70, 692], fill=(99, 102, 241, 255))
    d.text((92, 592), f"ENGINE 0{engine_no}", font=_font(26), fill=(129, 140, 248, 255))
    d.text((92, 624), name, font=_font(40), fill=(255, 255, 255, 255))
    d.text((92, 674), sub, font=_font(22, bold=False), fill=(148, 163, 184, 255))
    img.save(out)
    return out


# ── assembly ────────────────────────────────────────────────────────────────


def assemble() -> Path:
    missing = [k for k, _, _ in CHAPTERS if not _done(k).is_file()]
    if missing:
        raise SystemExit(f"chapters not generated yet: {', '.join(missing)}")
    score = WORK / "score.wav"
    if not score.is_file():
        raise SystemExit("score.wav not composed yet (--make score)")

    open_card = _card(
        [
            ("ONE STUDIO", 84, "#ffffff"),
            ("SIX ENGINES", 84, "#818cf8"),
            ("every frame generated in-house, today", 28, "#94a3b8"),
        ],
        WORK / "card_open.png",
    )
    end_card = _card(
        [
            ("ENGINE 06 — THE SCORE", 40, "#818cf8"),
            ("composed in code · you have been hearing it", 26, "#94a3b8"),
            ("", 20, "#0b1020"),
            ("+ verticals · locales · HUDs · QA · one dashboard", 30, "#ffffff"),
            ("RENDERED BY THE STUDIO", 48, "#ffffff"),
        ],
        WORK / "card_end.png",
    )

    segs: list[Path] = []

    def norm_card(png: Path, secs: float, out: Path):
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-loglevel",
                "error",
                "-loop",
                "1",
                "-t",
                str(secs),
                "-i",
                str(png),
                "-vf",
                # A slow push-in, not a static hold - reads as a shot, and
                # keeps the freeze detector meaningful for the generated
                # chapters.
                (
                    "scale=2560:1440,"
                    "zoompan=z='1+0.0009*on':d=1:"
                    "x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':"
                    f"s=1280x720:fps={FPS},format=yuv420p"
                ),
                "-frames:v",
                str(int(secs * FPS)),
                "-c:v",
                "libx264",
                "-crf",
                "16",
                str(out),
            ],
            check=True,
        )
        segs.append(out)

    norm_card(open_card, 4.0, WORK / "seg_open.mp4")

    for i, (key, name, sub) in enumerate(CHAPTERS, start=1):
        label = _label(i, name, sub, WORK / f"label_{key}.png")
        out = WORK / f"seg_{key}.mp4"
        # normalise, cap at 14s, label visible from 0.4s to 3s before the cut
        probe = subprocess.run(
            [
                "ffprobe",
                "-v",
                "error",
                "-show_entries",
                "format=duration",
                "-of",
                "csv=p=0",
                str(_done(key)),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        dur = min(float(probe.stdout.strip()), 14.0)
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-loglevel",
                "error",
                "-i",
                str(_done(key)),
                "-i",
                str(label),
                "-filter_complex",
                "[0:v]scale=1280:720:force_original_aspect_ratio=increase,"
                f"crop=1280:720,fps={FPS}[v];"
                f"[v][1:v]overlay=0:0:enable='between(t,0.4,{dur - 0.6:.2f})',"
                "format=yuv420p[out]",
                "-map",
                "[out]",
                "-t",
                f"{dur:.2f}",
                "-an",
                "-c:v",
                "libx264",
                "-crf",
                "16",
                str(out),
            ],
            check=True,
        )
        segs.append(out)

    # 4.5s, not 6: the composed score is exactly 60s, and the cut must end
    # inside it - a tail past the score reads as a silent dropout in QA and
    # to the ear.
    norm_card(end_card, 4.5, WORK / "seg_end.mp4")

    # crossfade chain
    durs = []
    for s in segs:
        probe = subprocess.run(
            [
                "ffprobe",
                "-v",
                "error",
                "-show_entries",
                "format=duration",
                "-of",
                "csv=p=0",
                str(s),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        durs.append(float(probe.stdout.strip()))
    xf = 0.5
    inputs: list[str] = []
    for s in segs:
        inputs += ["-i", str(s)]
    filters = []
    offset = 0.0
    prev = "[0:v]"
    for i in range(1, len(segs)):
        offset += durs[i - 1] - xf
        outlbl = f"[x{i}]" if i < len(segs) - 1 else "[vfinal]"
        filters.append(
            f"{prev}[{i}:v]xfade=transition=fade:duration={xf}:offset={offset:.2f}{outlbl}"
        )
        prev = outlbl
    total = offset + durs[-1]
    filters.append(
        f"[{len(segs)}:a]aresample=48000,apad,atrim=0:{total:.2f},"
        # level=0 matters: alimiter's default level=1 *boosts* the signal up
        # to the ceiling, the exact opposite of a safety limiter.
        # loudnorm outputs 192kHz; resample back to 48k BEFORE the limiter so
        # the limiter's ceiling is the last word - resampling after it can
        # overshoot, which is exactly how the first master clipped at 0dB.
        "loudnorm=I=-17:TP=-2:LRA=6,aresample=48000,"
        # -8dB ceiling: measured on this score, AAC encoding + inter-sample
        # true peak overshoot the pre-encode sample ceiling by ~4dB combined,
        # so the ceiling has to sit this low for the encoded TRUE peak to
        # come out at a legal ~-2dBTP. Loudness is set by loudnorm upstream,
        # so this only shaves transients.
        "alimiter=limit=0.4:level=0,"
        f"afade=t=in:d=1.2,afade=t=out:st={total - 2.5:.2f}:d=2.5[afinal]"
    )
    FINAL.parent.mkdir(parents=True, exist_ok=True)
    print("assemble filtergraph:", ";".join(filters), flush=True)
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-loglevel",
            "error",
            *inputs,
            "-i",
            str(score),
            "-filter_complex",
            ";".join(filters),
            "-map",
            "[vfinal]",
            "-map",
            "[afinal]",
            "-c:v",
            "libx264",
            "-crf",
            "16",
            "-preset",
            "medium",
            "-c:a",
            # Apple's AudioToolbox encoder, not ffmpeg's native aac: on this
            # percussive synth score the native encoder overshoots decoded
            # peaks by ~6dB (measured standalone), blowing any limiter
            # ceiling; aac_at stays within ~2dB.
            "aac_at",
            "-b:a",
            "256k",
            "-movflags",
            "+faststart",
            str(FINAL),
        ],
        check=True,
    )
    print(f"final={FINAL}  ({total:.1f}s)", flush=True)
    return FINAL


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--make",
        required=True,
        choices=["ltx", "flow", "manim", "remotion", "promo", "score", "assemble"],
    )
    args = ap.parse_args()
    WORK.mkdir(parents=True, exist_ok=True)
    fn = {
        "ltx": make_ltx,
        "flow": make_flow,
        "manim": make_manim,
        "remotion": make_remotion,
        "promo": make_promo,
        "score": make_score,
        "assemble": assemble,
    }[args.make]
    path = fn()
    print(f"done={path}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
